### ISSUE TITLE
Pressing XZ at the same time in main menu causes crash.

### ISSUE THREAD

**Issue by PyuuCH** [zeta0134/LuaGB#5] opened 2017-04-10 17:43 UTC
```
filebrowser.lua:195: attempt to concatenate local 'cursor_item' (a nil value)
Traceback:
filebrowser.lua:195: in function 'select_at_cursor'
filebrowser.lua:220: in function 'keyreleased'
main.lua:391: in function <main.lua:383:>
[C]: in function 'xpcall'
```

This applies to the Windows version.

**Comment by PyuuCH** [comment] 2017-04-10 17:58
This appears to only happen if there is no games available.

**Comment by sumit0190** [comment] 2017-04-11 23:39
I haven't played around with the emulator yet, but one glance at the code tells me that this can be reproduced by just pressing X on a screen where no games are available (on any OS). It's because there is no 'nil check' in the `select_at_cursor` function - ideally, the code from line 195 onwards (in `filebrowser.lua`) would be executed only if `cursor_item` is non-nil. There should probably be a few other checks as well, I think. @zeta0134 is my analysis correct?

**Comment by zeta0134** [comment] 2017-04-11 23:53
Aye, your analysis was spot on. Fixed by: https://github.com/zeta0134/LuaGB/commit/8c7fcc0153ecd6f0b7442cef8d110f36a923c62f

**Closed by zeta0134** 2017-04-11 23:53 UTC
